name: vybecabs_rider
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+100

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.15.0
  firebase_auth: ^6.7.0
  google_maps_flutter: ^2.18.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.5
  intl: ^0.20.2
  uuid: ^4.5.1
  geolocator: ^13.0.2
  geocoding: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800

